version: "3.9"
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app/app
      - ./alembic:/usr/src/app/alembic
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1111
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=fastapi
      - SECRET_KEY=7231be4dd761d17a0ec22e0e0930e665a8881108ea1e429f9eecb155116323a5
      - ALGORITHM=HS256
      - access_token_expire_minutes=60

  db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=fastapi
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
